name: Deploy to IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install @pinata/sdk

    - name: Deploy to IPFS with Pinata
      run: |
        node <<EOF
        const pinataSDK = require('@pinata/sdk');
        const fs = require('fs');
        const pinata = pinataSDK(process.env.PINATA_API_KEY, process.env.PINATA_API_SECRET);

        async function deploy() {
            const options = {
                pinataMetadata: { name: 'Decentralized Website' },
                pinataOptions: { cidVersion: 0 }
            };

            const readableStreamForFile = fs.createReadStream('./index.html');
            const result = await pinata.pinFileToIPFS(readableStreamForFile, options);
            console.log('Pinned to IPFS:', result);
        }

        deploy().catch(console.error);
        EOF
      env:
        PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
        PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
