- name: Deploy to IPFS
  uses: aquiladev/ipfs-action@master
  with:
    path: ./pinataWebsite/index.html
    service: pinata
    pinataKey: ${{ secrets.PINATA_API_KEY }}
    pinataSecret: ${{ secrets.PINATA_API_SECRET }}