name: Deploy to IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Pinata SDK
      run: npm install @pinata/sdk

    - name: Deploy to IPFS with Pinata
      run: |
        node <<EOF
        const pinataSDK = require('@pinata/sdk');
        const fs = require('fs');
        const path = require('path');
        
        const pinata = pinataSDK(process.env.PINATA_API_KEY, process.env.PINATA_API_SECRET);

        async function deploy() {
            const folderPath = './';
            const files = fs.readdirSync(folderPath);
            
            for (const file of files) {
                const filePath = path.join(folderPath, file);
                const stats = fs.statSync(filePath);

                if (stats.isFile()) {
                    const readableStreamForFile = fs.createReadStream(filePath);
                    const options = {
                        pinataMetadata: {
                            name: file
                        },
                        pinataOptions: {
                            cidVersion: 0
                        }
                    };

                    try {
                        const result = await pinata.pinFileToIPFS(readableStreamForFile, options);
                        console.log(`File pinned: ${file} - CID: ${result.IpfsHash}`);
                    } catch (error) {
                        console.error(`Error pinning file: ${file}`, error);
                    }
                }
            }
        }

        deploy().catch(console.error);
        EOF
      env:
        PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
        PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
